[theme]
base = "dark"
primaryColor = "#2ea44f"               
backgroundColor = "#0d1117"            
secondaryBackgroundColor = "#161b22"   
textColor = "#c9d1d9"                  
font = "roboto"

[server]
runOnSave = true

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[browser]
gatherUsageStats = false
